fix: some fix
Romaleso261981/command-project pull request #9
Opened 2024-01-25 13:56 UTC by Romaleso261981

2024-01-28 17:14 UTC, remadyt requested changes

2024-01-28 17:14 UTC, remadyt commented on .env.exampele
> +VITE_API_KEY = 'Api key'
оставь здесь актульные ключи, их должна видеть вся команда

2024-01-28 17:14 UTC, remadyt commented on postcss.config.cjs
> +module.exports = {
не используем пост цсс
сноси это

2024-01-28 17:14 UTC, remadyt commented on src/App/Layout.module.css
не верный нейминг или неправлиьно местоположение

2024-01-28 17:14 UTC, remadyt commented on src/App/Layout.module.css
> +.main{
зачем нужен пустой класс?

2024-01-28 17:14 UTC, remadyt commented on src/App/RootRouter.tsx
> +import { Spiner } from '@/shared/components/Loader/Loader';
используй index.ts
путь должен быть @shared/components
актуально для всех мест

2024-01-28 17:14 UTC, remadyt commented on src/App/RootRouter.tsx
> +          <Route path="/login" element={<AuthPage />} />
сделай енамку для роутов

2024-01-28 17:14 UTC, remadyt commented on src/shared/components/Header/Header.module.css
> +/* .root::after {
удали и хватит оставлять закоменнченный код
пробегайся сам по пру, уже кучу раз писал тебе коммент об этом

2024-01-28 17:14 UTC, remadyt commented on src/shared/components/Header/ui/components/Messages/Messages.tsx
> +          colorScheme === 'dark' ? theme.colors.gray[7] : theme.colors.gray[3]
что будешь делать если добавиться еще несколько цветовых схем? предлагаю пересмореть этот костыль

2024-01-28 17:14 UTC, remadyt commented on src/shared/components/Header/ui/components/Messages/data.ts
> +export const ICON_SIZE = 20;
размеры иконок не стоит выносить в коснатнту, использую дефолтные размеры xs, md и тд

2024-01-28 17:14 UTC, remadyt commented on src/shared/components/Header/ui/components/Navbar/Navbar.module.css
> +  /* background-color: var(--mantine-color-blue-filled); */
удали

2024-01-28 17:14 UTC, remadyt commented on src/shared/components/Header/ui/components/Navbar/Navbar.tsx
> +function NavbarLink({ icon: Icon, label, active, onClick, path }: NavbarLinkProps) {
повыноси в компоненты на компоненты?

2024-01-28 17:14 UTC, remadyt commented on src/shared/components/Header/ui/components/Navbar/Navbar.tsx
> +export function Navbar() {
используем везде стрелочные функции

2024-01-28 17:14 UTC, remadyt commented on src/shared/components/Header/ui/components/Navbar/Navbar.tsx
> +          <NavbarLink path="/admin/1" icon={IconFingerprint} label="Profile" />
что значит админ 1?

2024-01-28 17:14 UTC, remadyt commented on src/shared/components/Header/ui/components/UserInfo/UserInfo.tsx
> +    localStorage.setItem(
сделай хелперы для работы с локалсторалджем

2024-01-29 08:25 UTC, Romaleso261981 commented on src/shared/components/Header/ui/components/Navbar/Navbar.tsx
> +function NavbarLink({ icon: Icon, label, active, onClick, path }: NavbarLinkProps) {
Не зрозумів. Мені винести компоненти які я використовую в header в загальні компоненти? Я NavbarLink використовую тільки в header.

2024-02-01 11:51 UTC, AdammmVV commented on src/pages/AuthPage/ui/auth-ui-form.tsx
>              onChange={(event) => form.setFieldValue('email', event.currentTarget.value)}
Why don't you use [getinputprops ](https://mantine.dev/form/get-input-props/#getinputprops-handler) here and all forms?

2024-02-01 11:51 UTC, AdammmVV commented on src/pages/MainPage/MainPage.tsx
> +        <h1>MainPage</h1>
use mantine components

2024-02-01 11:51 UTC, AdammmVV commented on src/shared/components/Header/ui/LanguagePicker/LanguagePicker.tsx
>  ];
put it in config file

2024-02-01 11:51 UTC, AdammmVV commented on src/shared/components/Header/ui/LanguagePicker/LanguagePicker.tsx
> +  const initialLeng = data.find((i) => i.label === getLocalStorage('i18nextLng')) ?? data[0];
try to simplify this

2024-02-01 11:51 UTC, AdammmVV commented on src/shared/components/Header/ui/LanguagePicker/LanguagePicker.tsx
> +export const LanguagePicker = ({ type }: LanguagePickerProps) => {
place the props typing for the component near the component `LanguagePickerProps`

2024-02-01 11:51 UTC, AdammmVV commented on src/shared/components/Header/ui/Messages/Messages.tsx
> +          colorScheme === 'dark' ? theme.colors.gray[7] : theme.colors.gray[3]
try use [style-prop](https://mantine.dev/styles/styles-overview/#style-prop) with css variables and read about using [data-mantine-color-scheme-attribute](https://mantine.dev/theming/color-schemes/#data-mantine-color-scheme-attribute) or use `light-dark`

2024-02-01 11:51 UTC, AdammmVV commented on src/shared/components/Header/ui/Messages/Messages.tsx
> +export const Messages = () => {
format the component, separate the logic with empty lines

2024-02-01 11:51 UTC, AdammmVV commented on src/shared/components/Header/ui/Navbar/Navbar.tsx
> +}
put it in separate file

2024-02-01 11:51 UTC, AdammmVV commented on src/shared/components/Header/ui/Notification/Notification.tsx
> +        }`
try use [style-prop](https://mantine.dev/styles/styles-overview/#style-prop) with css variables and read about using [data-mantine-color-scheme-attribute](https://mantine.dev/theming/color-schemes/#data-mantine-color-scheme-attribute) or use light-dark

2024-02-01 11:51 UTC, AdammmVV commented on src/shared/components/Header/ui/Messages/Messages.tsx
> +          {Array.from(m.last_name)[0]}
can't it be made simpler?

2024-02-01 11:51 UTC, AdammmVV commented on src/shared/components/Header/ui/Search/Search.module.css
> +}
what is this for?

2024-02-01 11:51 UTC, AdammmVV commented on src/shared/components/Header/ui/Notification/Notification.tsx
> +    </Menu.Item>
try to make this component universal for `MESSAGES`

2024-02-01 11:51 UTC, AdammmVV commented on src/shared/components/Header/ui/UserInfo/UserInfo.tsx
> +            <div style={{ flex: 1 }}>
why don't you use it mantine component?

2024-02-02 10:05 UTC, merged